---
- name: Evaluate {{ operators_project }} namespace if not exists
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ operators_project }}'
    state: present
  when:
    - operators_project is defined
    - operators_project | trim() != "openshift-operators"     

- name: Evaluate Operator Group
  k8s:
    api_version: operators.coreos.com/v1alpha2
    kind: OperatorGroup
    name: workshop-operators
    namespace: '{{ operators_project }}'
  when:
    - operators_project is defined
    - operators_project | trim() != "openshift-operators"     

- name: Evaluate AMQ Broker Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'broker-subscription.yaml.j2') }}"

- name: Wait for AMQ Broker operator to install
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: activemqartemises.broker.amq.io
  register: crd_broker
  until: crd_broker.resources | list | length == 1
  retries: 10
  delay: 30
