---
- name: Install Edge-to-Core Solution Pattern Demo
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - name: Install
      ansible.builtin.include_role:
        name: install
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"

    - name: Uninstall
      ansible.builtin.include_role:
        name: uninstall
      when: >
        ACTION is defined and
        ACTION | trim() == "remove"
