- name: Collect NooBaa Buckets
  k8s_info:
    api_version: objectbucket.io/v1alpha1
    kind: ObjectBucketClaim
  register: buckets_list

- name: Print buckets_list
  debug:
    msg: "result: {{ item.metadata.name }} "
  loop: '{{ buckets_list.resources }}'

- name: Delete NooBaa Buckets
  k8s:
    state: absent
    api_version: objectbucket.io/v1alpha1
    kind: ObjectBucketClaim
    name: '{{ item.metadata.name }}'
    namespace: '{{ odf_project }}'
  loop: '{{ buckets_list.resources }}'

