- name: Collect all CheCluster instances
  k8s_info:
    api_version: org.eclipse.che/v2
    kind: CheCluster
  register: checluster_found

- name: Debug CheCluster instances
  debug:
    msg: "{{item.metadata.name}}"
  loop: '{{ checluster_found.resources }}'

- name: Delete CheCluster instances
  when: checluster_found.api_found is true
  k8s:
    state: absent
    api_version: org.eclipse.che/v2
    kind: CheCluster
    name: '{{item.metadata.name}}'
    namespace: '{{item.metadata.namespace}}'
  loop: '{{ checluster_found.resources }}'


- name: Delete DevSpaces subscription
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: devspaces
    namespace: '{{ operators_project }}'

- name: Get DevSpaces CSV name
  shell: 
    cmd: >
      oc get csv -o name -n {{ operators_project }} 
      | grep devspacesoperator 
      | xargs oc get -o json -n {{ operators_project }}
      | jq .metadata.name -r
  register: sub_devspaces_name

- name: Print sub_devspaces_name
  debug:
    msg: "result: {{ sub_devspaces_name }} "

- name: Delete DevSpaces Operator
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ sub_devspaces_name.stdout }}"
    namespace: '{{ operators_project }}'

- name: Delete CHE namespace
  k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: '{{ che_project }}'